app = "globalconfig-dht"

# make doesn't pass SIGINT?
kill_signal = "SIGKILL"
kill_timeout = 5

[experimental]
  entrypoint = ["./run"]
  cmd = []
  # 42070 is for testing public port behaviour
  allowed_public_ports = [42069, 42070]

[[services]]
  internal_port = 42069
  protocol = "tcp"

  [[services.ports]]
    port = 42069

  [[services.tcp_checks]]
    # Wait for first publish
    grace_period = "5m"
    # How do we handle down time during DHT publishes?
    interval = "60s"
    timeout = "5m"

[[services]]
  internal_port = 42069
  protocol = "udp"

  [[services.ports]]
    port = 42069
